import React from 'react'

const ComponenteCommon2 = () => <div>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ultricies velit nec mauris pellentesque, sed molestie eros laoreet. Proin semper, massa in blandit tempor, metus massa fringilla velit, quis consectetur dui mauris at mauris. In hac habitasse platea dictumst. Sed faucibus malesuada ante ac molestie. Pellentesque id odio quis mi efficitur lobortis non quis orci. Donec non hendrerit ante. Sed lobortis ut nibh dapibus efficitur. Vivamus ex enim, egestas id tincidunt ac, eleifend vitae risus. Suspendisse in vulputate felis. In scelerisque et nulla pulvinar efficitur. Maecenas urna odio, volutpat a vestibulum at, elementum sit amet neque. Praesent faucibus sapien eu neque pulvinar, in vestibulum ligula viverra. Aliquam et quam in sem pharetra interdum non non lacus.

Etiam id euismod lorem, et blandit tellus. Pellentesque id dui sapien. Vivamus eu ante lorem. Donec sagittis mauris augue, sagittis auctor odio efficitur id. Integer lacus lacus, laoreet at aliquam at, tempus non mauris. Etiam nisi risus, cursus vel mauris eget, facilisis aliquam nisl. Maecenas ut tellus nisl.

Phasellus vel placerat libero, vel luctus est. Morbi leo risus, pellentesque a eleifend non, convallis vel justo. Nulla posuere venenatis varius. Morbi ante neque, molestie eu risus pharetra, maximus gravida ligula. Phasellus laoreet tincidunt est, vitae tristique nibh. Aliquam erat volutpat. Quisque dignissim lacus eu ipsum dapibus, feugiat facilisis ligula aliquet. Nulla tincidunt a nisl eget ultrices. Duis tincidunt imperdiet libero vitae elementum.

Nunc vel tempor nisl. Nam convallis elit vitae laoreet mattis. Curabitur imperdiet, purus eget euismod placerat, nisl nunc sollicitudin nunc, id porttitor metus urna eget eros. Nunc accumsan sagittis mi, quis pellentesque felis faucibus quis. Mauris aliquam nisl vel mi commodo cursus. Proin commodo consequat ipsum, mollis tincidunt nisl. Nam nec risus et quam fermentum laoreet sit amet eget sem. Nunc sed purus lobortis, aliquam urna vitae, interdum massa. Suspendisse maximus venenatis neque, in ornare lorem rhoncus nec. Sed ac hendrerit eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Mauris fermentum ex eu est ultricies venenatis sed id justo. Proin quis orci blandit, finibus nisl a, commodo lacus. Nam fringilla mi id mi scelerisque varius. Mauris sed sem nec tellus suscipit faucibus. Morbi suscipit sed leo eu rutrum. Mauris laoreet maximus tempus. Aenean at luctus dui. Pellentesque suscipit massa velit, quis vehicula odio faucibus sit amet. Duis ullamcorper porta dolor vel faucibus. Donec pharetra auctor faucibus. Etiam sed urna non ipsum volutpat sollicitudin. Aliquam nec justo ultrices, condimentum sem eget, consectetur dui. Maecenas tristique, sapien nec mattis maximus, purus ante rhoncus nisl, quis sodales magna mauris a ante. Sed vel libero ipsum.</div>

export default ComponenteCommon2